# Generated by Django 4.2.7 on 2025-11-12 09:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], default='ADMIN', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NurseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (6AM - 2PM)'), ('AFTERNOON', 'Afternoon (2PM - 10PM)'), ('NIGHT', 'Night (10PM - 6AM)')], max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('certifications', models.TextField(blank=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nurse Detail',
                'verbose_name_plural': 'Nurse Details',
            },
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('PULMONOLOGY', 'Pulmonology'), ('CRITICAL_CARE', 'Critical Care'), ('CARDIOLOGY', 'Cardiology'), ('EMERGENCY', 'Emergency Medicine'), ('NEUROLOGY', 'Neurology'), ('SURGERY', 'Surgery'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('GENERAL', 'General Medicine')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('certifications', models.TextField(blank=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Detail',
                'verbose_name_plural': 'Doctor Details',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staff.customuser',),
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Nurse',
                'verbose_name_plural': 'Nurses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staff.customuser',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (6AM - 2PM)'), ('AFTERNOON', 'Afternoon (2PM - 10PM)'), ('NIGHT', 'Night (10PM - 6AM)')], max_length=20)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'NURSE']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Schedule',
                'verbose_name_plural': 'Staff Schedules',
                'ordering': ['-date', 'shift'],
                'unique_together': {('staff', 'date', 'shift')},
            },
        ),
    ]
