# Generated by Django 4.2.7 on 2025-11-12 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily, Every 6 hours', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days, 2 weeks', max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation')], default='ORAL', max_length=20)),
                ('instructions', models.TextField(help_text='Special instructions for administration')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('treatment_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treatment Plan',
                'verbose_name_plural': 'Treatment Plans',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('action_type', models.CharField(choices=[('REGISTRATION', 'Patient Registration'), ('ADMISSION', 'Admission'), ('PRESCRIPTION', 'Prescription Added'), ('TREATMENT', 'Treatment Plan Added'), ('VITALS', 'Vitals Recorded'), ('PROCEDURE', 'Procedure Performed'), ('DISCHARGE', 'Discharge'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patients.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.prescription')),
                ('related_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.treatment')),
            ],
            options={
                'verbose_name': 'Treatment History',
                'verbose_name_plural': 'Treatment Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('ELECTIVE', 'Elective'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('admission_datetime', models.DateTimeField()),
                ('room_number', models.CharField(max_length=10)),
                ('chief_complaint', models.TextField(help_text='Primary reason for admission')),
                ('initial_bp_systolic', models.IntegerField()),
                ('initial_bp_diastolic', models.IntegerField()),
                ('initial_heart_rate', models.IntegerField()),
                ('initial_temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('initial_oxygen', models.IntegerField()),
                ('emergency_contact_verified', models.BooleanField(default=False)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(limit_choices_to={'role__in': ['NURSE', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Admission Record',
                'verbose_name_plural': 'Admission Records',
                'ordering': ['-admission_datetime'],
            },
        ),
    ]
